# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40fc7b8337c006f618c3f045a8853b228fc8a7c4e930e4cd9884f07ed694f72a7fe5c63dbe0c41e3047f9a9c00396d8607922efa7838cd578d2d012e694c8bf0

test:
  secret_key_base: f842f308a5da0283d678bfb872b769e3a239e8b3bfc278e9d98ef4c2c8548e68ea56c4a55f7d13775332850a077397806668ccddd8a85222500c7ecb30cd589f

production:
  secret_key_base: 8ac6579356ec853e775f1d9be2e12c1d5d682c801af2d41a1a7eae07b4a9b3421fad8ebef0e6c6e6aec432cf2d9d14dfe93acfd7cdcce76ee1f329a80346cbc9
